### ISSUE TITLE
Add previews to videos list page

### ISSUE THREAD

**Issue by Hebo** [Hebo/chompy#6]
Add a preview image for files in `/videos`

**Tasks**

- [ ] Have YouTube-dl download previews (--write-thumbnail)
- [ ] Render thumbnail in videos list page
- [ ] Prevent thumbnail files from being treated as videos in disk operations (getting videos, deleting)
- [ ] Make sure thumbnails are deleted alongside videos
